### ISSUE TITLE
Problems encountered during testing

### ISSUE THREAD

**Issue by 309020726** [CAMMA-public/SelfSupSurg#7]
Hello, I would like to test the surgical tool recognition using the trained weights first, but I have encountered the following issue:

Code running instructions:
(selfsupsurg)>cfg=hparams/cholec80/finetuning/cholec_to_cholec/series_01/test/tools/25/0/h001.yaml
(selfsupsurg)>python main.py -hp $cfg -m supervised

error：
Traceback (most recent call last):
  File "main.py", line 99, in <module>
    hydra_main(overrides=overrides, mode=training_mode)
  File "main.py", line 61, in hydra_main
    launch_distributed(
  File "/home/liu/disk2/lxj/SelfSupSurg/SelfSupSurg-main/ext_libs/vissl/vissl/utils/distributed_launcher.py", line 152, in launch_distributed
    _distributed_worker(
  File "/home/liu/disk2/lxj/SelfSupSurg/SelfSupSurg-main/ext_libs/vissl/vissl/utils/distributed_launcher.py", line 194, in _distributed_worker
    run_engine(
  File "/home/liu/disk2/lxj/SelfSupSurg/SelfSupSurg-main/ext_libs/vissl/vissl/engines/engine_registry.py", line 86, in run_engine
    engine.run_engine(
  File "/home/liu/disk2/lxj/SelfSupSurg/SelfSupSurg-main/ext_libs/vissl/vissl/engines/train.py", line 39, in run_engine
    train_main(
  File "/home/liu/disk2/lxj/SelfSupSurg/SelfSupSurg-main/ext_libs/vissl/vissl/engines/train.py", line 130, in train_main
    trainer.train()
  File "/home/liu/disk2/lxj/SelfSupSurg/SelfSupSurg-main/ext_libs/vissl/vissl/trainer/trainer_main.py", line 162, in train
    self.task.prepare(pin_memory=self.cfg.DATA.PIN_MEMORY)
  File "/home/liu/disk2/lxj/SelfSupSurg/SelfSupSurg-main/ext_libs/vissl/vissl/trainer/train_task.py", line 735, in prepare
    self.datasets, self.data_and_label_keys = self.build_datasets(
  File "/home/liu/disk2/lxj/SelfSupSurg/SelfSupSurg-main/ext_libs/vissl/vissl/trainer/train_task.py", line 308, in build_datasets
    datasets[split.lower()] = build_dataset(
  File "/home/liu/disk2/lxj/SelfSupSurg/SelfSupSurg-main/ext_libs/vissl/vissl/data/__init__.py", line 72, in build_dataset
    return GenericSSLDataset(
  File "/home/liu/disk2/lxj/SelfSupSurg/SelfSupSurg-main/ext_libs/vissl/vissl/data/ssl_dataset.py", line 105, in __init__
    self._get_data_files(split)
  File "/home/liu/disk2/lxj/SelfSupSurg/SelfSupSurg-main/ext_libs/vissl/vissl/data/ssl_dataset.py", line 159, in _get_data_files
    self.data_paths, self.label_paths = dataset_catalog.get_data_files(
  File "/home/liu/disk2/lxj/SelfSupSurg/SelfSupSurg-main/ext_libs/vissl/vissl/data/dataset_catalog.py", line 262, in get_data_files
    assert len(dataset_config[split].DATASET_NAMES) == len(
AssertionError: len(data_sources) != len(dataset_names)

I output these two parameters with  “print(dataset_config[split].DATASET_NAMES)
                                                            print(dataset_config[split].DATA_SOURCES)”
and the result is:
['imagenet1k_folder']
[]

I was wondering if I wanted to change the data path in h001.yaml to my own, but I don't know what the difference between DATA_PATHS and DATA_SOURCES is? Is DATA_SOURCES the path to write videos for the Cholec80 dataset?
Can you provide detailed information on the points that need to be changed in the configuration file?

I am looking forward to your reply and would greatly appreciate it.   ^_^

**Comment by vinkle** [comment]
#### Modify `$SelfSupSurg/ext_libs/vissl/configs/config/dataset_catalog.json` by appending the following key/value pair to the end of the dictionary

```json
"surgery_datasets": {
    "train": ["<img_path>", "<lbl_path>"],
    "val": ["<img_path>", "<lbl_path>"],
    "test": ["<img_path>", "<lbl_path>"]
}
```

Hi have you followed these instructions from the readme to update the `dataset_catalog.json` file?

**Comment by 309020726** [comment]
Hello, I have already added the following text to the ‘dataset_catalog.json’ file before asking you a question：
"surgery_datasets": {
    "train": ["<img_path>", "<lbl_path>"],
    "val": ["<img_path>", "<lbl_path>"],
    "test": ["<img_path>", "<lbl_path>"]
}
And then the above-mentioned problems emerged.

**Comment by 309020726** [comment]
”hparams/cholec80/finetuning/cholec_to_cholec/series_01/test/tools/25/0/h001.yaml“ 
May I ask if the DATA_SOURCES in this configuration file needs to be changed to the original video path of the Cholec80 dataset???
If so, does LABEL_SOURCES refer to the ”tool_annotations“ file in the Cholec80 dataset? Or what other label file path is it?

ps："tool_annotations"——The file is a tool label file that comes with the Cholec80 dataset

**Comment by 309020726** [comment]
Thank you for your reply. I have already updated the file before this.

I have identified the problem and found the following code in "main. py":
Cfg=composite ("defaults", covers=covers)
The corresponding parameters in "extunlibs/vissl/vissl/configure/defaults. yaml" are as follows:
DATASETNAMES: ["imagenet1k_folder"] and LABEL_SOURCES: []
So much so that the above-mentioned problems occur.

May I ask what is the purpose of this? How can I solve this problem now?

**Comment by 309020726** [comment]
Thank you for your reply. I have already updated the file before this.

I have identified the problem and found the following code in "main. py":
cfg=composite ("defaults", covers=covers)
The corresponding parameters in "extunlibs/vissl/vissl/configure/defaults. yaml" are as follows:
DATASETNAMES: ["imagenet1k_folder"] and LABEL_SOURCES: []
It seems that the issue occurred because the two configuration files "default. yaml" and "h001. yaml" were not updated in content and were simply overlaid, resulting in this issue.

May I ask how can I solve this problem now?
